In [ ]:
F1 = [12, 4, 8, 17]
F2 = [5, 9, 16, 7]

In [6]:
import numpy as np

# Step 1: Define the dataset
X = np.array([
    [4, 11],
    [8, 4],
    [13, 5],
    [7, 14]
])
print("Step 1: The given dataset:")
print(X)

# Step 2: Center the data
mean = np.mean(X, axis=0)
X_centered = X - mean
print("\nStep 2: Centered data:")
print(X_centered)

# Step 3: Compute the covariance matrix
C = np.cov(X_centered, rowvar=False)
print("\nStep 3: Covariance matrix:")
print(C)

# Step 4: Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(C)
print("\nStep 4: Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

# Step 5: Sort eigenvalues and eigenvectors
sorted_indices = np.argsort(eigenvalues)[::-1]  # Sort in descending order
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]
print("\nStep 5: Sorted eigenvalues:")
print(sorted_eigenvalues)
print("\nSorted eigenvectors:")
print(sorted_eigenvectors)

# Step 6: Project the data onto the principal components
# Select the eigenvector corresponding to the largest eigenvalue
principal_component = sorted_eigenvectors[:, 0]
X_pca = np.dot(X_centered, principal_component)
print("\nStep 6: Projected data (PCA):")
print(X_pca)

# Step 7: Final transformed data
print("\nStep 7: Final transformed data in PCA space:")
print(X_pca)

Step 1: The given dataset:
[[ 4 11]
 [ 8  4]
 [13  5]
 [ 7 14]]

Step 2: Centered data:
[[-4.   2.5]
 [ 0.  -4.5]
 [ 5.  -3.5]
 [-1.   5.5]]

Step 3: Covariance matrix:
[[ 14. -11.]
 [-11.  23.]]

Step 4: Eigenvalues:
[ 6.61513568 30.38486432]

Eigenvectors:
[[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]

Step 5: Sorted eigenvalues:
[30.38486432  6.61513568]

Sorted eigenvectors:
[[ 0.55738997 -0.83025082]
 [-0.83025082 -0.55738997]]

Step 6: Projected data (PCA):
[-4.30518692  3.73612869  5.69282771 -5.12376947]

Step 7: Final transformed data in PCA space:
[-4.30518692  3.73612869  5.69282771 -5.12376947]
