In [1]:
# Solution PCA
import numpy as np

F1 = [12, 4, 8, 17]
F2 = [5, 9, 16, 7]

X = np.array([F1, F2])
print("\nThe given dataset: \n", np.transpose(X))

CovX = np.cov(X)
print("\nThe Covariance Matrx: \n", CovX)

EigValue = np.linalg.eig(CovX)[0]
EigVector = np.linalg.eig(CovX)[1]
print("\nThe Eigen Values are: \n" , EigValue)
print("\nThe Eigen Vector are: \n" , EigVector)


print("\nThe Projected Dataset: " )
redData = np.matmul(np.transpose(X), EigVector[0])
print(redData)


The given dataset: 
 [[12  5]
 [ 4  9]
 [ 8 16]
 [17  7]]

The Covariance Matrx: 
 [[ 30.91666667 -12.08333333]
 [-12.08333333  22.91666667]]

The Eigen Values are: 
 [39.64486153 14.1884718 ]

The Eigen Vector are: 
 [[ 0.81063646  0.58554977]
 [-0.58554977  0.81063646]]

The Projected Dataset: 
[12.65538636  8.51249373 15.85388793 17.8796682 ]
