In [1]:
import torch
import numpy as np

In [2]:
# Input (x, y, z)
inputs = np.array([[75, 63, 48], 
                   [91, 88, 66], 
                   [84, 137, 57], 
                   [108, 41, 36], 
                   [68, 98, 72]], dtype='float32')

In [3]:
# Targets (a, b)
targets = np.array([[54, 71], 
                    [84, 111], 
                    [122, 143], 
                    [20, 40], 
                    [101, 117]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 75.,  63.,  48.],
        [ 91.,  88.,  66.],
        [ 84., 137.,  57.],
        [108.,  41.,  36.],
        [ 68.,  98.,  72.]])
tensor([[ 54.,  71.],
        [ 84., 111.],
        [122., 143.],
        [ 20.,  40.],
        [101., 117.]])


In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.1463,  0.1394,  0.1724],
        [-0.4648, -2.1807,  0.0460]], requires_grad=True)
tensor([0.3225, 1.2896], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [8]:
# Train for 200 epochs
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [9]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(85.9070, grad_fn=<DivBackward0>)


In [10]:
# Predictions
preds

tensor([[ 57.4216,  79.7738],
        [ 82.0295, 110.1118],
        [119.1781, 123.7114],
        [ 29.2001,  56.0922],
        [ 96.4517, 121.6273]], grad_fn=<AddBackward0>)

In [11]:
# Targets
targets

tensor([[ 54.,  71.],
        [ 84., 111.],
        [122., 143.],
        [ 20.,  40.],
        [101., 117.]])