In [40]:
!pip install torch_optimizer
!pip install adabelief_pytorch==0.2.0

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch_optimizer as optim
from adabelief_pytorch import AdaBelief
import numpy as np


# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            

# Input (x, y, z)
inputs = np.array([[75, 63, 48], 
                   [91, 88, 66], 
                   [84, 137, 57], 
                   [108, 41, 36], 
                   [68, 98, 72]], dtype='float32')

# Targets (a, b)
targets = np.array([[54, 71], 
                    [84, 111], 
                    [122, 143], 
                    [20, 40], 
                    [101, 117]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

# Define data loader
batch_size = 2  # should be << number of observations
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break
    
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

# Define loss function
loss_fn = F.mse_loss

#Adam Optimizer
opt = torch.optim.Adam(model.parameters(), lr = 1e-3, betas= (0.9, 0.99))

fit(1000, model, loss_fn, opt, train_dl)

tensor([[ 75.,  63.,  48.],
        [ 91.,  88.,  66.],
        [ 84., 137.,  57.],
        [108.,  41.,  36.],
        [ 68.,  98.,  72.]])
tensor([[ 54.,  71.],
        [ 84., 111.],
        [122., 143.],
        [ 20.,  40.],
        [101., 117.]])
tensor([[108.,  41.,  36.],
        [ 91.,  88.,  66.]])
tensor([[ 20.,  40.],
        [ 84., 111.]])
Parameter containing:
tensor([[ 0.2608,  0.1790, -0.1053],
        [ 0.1324,  0.3835,  0.2911]], requires_grad=True)
Parameter containing:
tensor([ 0.4452, -0.1998], requires_grad=True)
Epoch [10/1000], Loss: 151.2701
Epoch [20/1000], Loss: 1369.3306
Epoch [30/1000], Loss: 159.7799
Epoch [40/1000], Loss: 720.9719
Epoch [50/1000], Loss: 708.2392
Epoch [60/1000], Loss: 1132.3232
Epoch [70/1000], Loss: 1010.6023
Epoch [80/1000], Loss: 755.7871
Epoch [90/1000], Loss: 633.9187
Epoch [100/1000], Loss: 520.8732
Epoch [110/1000], Loss: 448.6373
Epoch [120/1000], Loss: 1425.9229
Epoch [130/1000], Loss: 412.9175
Epoch [140/1000], Loss: 372.8903
Epo

In [2]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 55.7432,  73.5533],
        [ 81.0681, 104.2623],
        [124.9522, 144.0197],
        [ 22.3101,  42.0516],
        [ 98.5910, 120.0431]], grad_fn=<AddmmBackward>)

In [3]:
model(torch.tensor([[72, 65., 42.]]))  #testing

tensor([[56.2263, 72.2677]], grad_fn=<AddmmBackward>)

In [4]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch_optimizer as optim
from adabelief_pytorch import AdaBelief
import numpy as np


# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            

# Input (x, y, z)
inputs = np.array([[75, 63, 48], 
                   [91, 88, 66], 
                   [84, 137, 57], 
                   [108, 41, 36], 
                   [68, 98, 72]], dtype='float32')

# Targets (a, b)
targets = np.array([[54, 71], 
                    [84, 111], 
                    [122, 143], 
                    [20, 40], 
                    [101, 117]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

# Define data loader
batch_size = 2  # should be << number of observations
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break
    
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

# Define loss function
loss_fn = F.mse_loss

# RMSprop Optimizer
opt = torch.optim.RMSprop(model.parameters(), lr = 1e-3, alpha = 0.9)

fit(1000, model, loss_fn, opt, train_dl)

tensor([[ 75.,  63.,  48.],
        [ 91.,  88.,  66.],
        [ 84., 137.,  57.],
        [108.,  41.,  36.],
        [ 68.,  98.,  72.]])
tensor([[ 54.,  71.],
        [ 84., 111.],
        [122., 143.],
        [ 20.,  40.],
        [101., 117.]])
tensor([[108.,  41.,  36.],
        [ 75.,  63.,  48.]])
tensor([[20., 40.],
        [54., 71.]])
Parameter containing:
tensor([[-0.1411,  0.2815, -0.0965],
        [ 0.0735, -0.2701,  0.2017]], requires_grad=True)
Parameter containing:
tensor([-0.1614,  0.0841], requires_grad=True)
Epoch [10/1000], Loss: 8099.4263
Epoch [20/1000], Loss: 417.1291
Epoch [30/1000], Loss: 12522.0059
Epoch [40/1000], Loss: 6698.9771
Epoch [50/1000], Loss: 1407.1208
Epoch [60/1000], Loss: 1096.3097
Epoch [70/1000], Loss: 4128.1685
Epoch [80/1000], Loss: 2240.5576
Epoch [90/1000], Loss: 411.6175
Epoch [100/1000], Loss: 4402.8174
Epoch [110/1000], Loss: 448.1182
Epoch [120/1000], Loss: 1499.8447
Epoch [130/1000], Loss: 573.7936
Epoch [140/1000], Loss: 945.6118
E

In [5]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 55.9039,  75.3351],
        [ 81.9113, 105.6856],
        [122.8778, 137.4829],
        [ 20.2848,  47.1356],
        [100.8588, 119.5984]], grad_fn=<AddmmBackward>)

In [6]:
model(torch.tensor([[72, 65., 42.]]))  #testing

tensor([[55.6298, 72.9180]], grad_fn=<AddmmBackward>)

In [7]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch_optimizer as optim
from adabelief_pytorch import AdaBelief
import numpy as np


# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            

# Input (x, y, z)
inputs = np.array([[75, 63, 48], 
                   [91, 88, 66], 
                   [84, 137, 57], 
                   [108, 41, 36], 
                   [68, 98, 72]], dtype='float32')

# Targets (a, b)
targets = np.array([[54, 71], 
                    [84, 111], 
                    [122, 143], 
                    [20, 40], 
                    [101, 117]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

# Define data loader
batch_size = 2  # should be << number of observations
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break
    
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

# Define loss function
loss_fn = F.mse_loss

# SGD Optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

fit(1000, model, loss_fn, opt, train_dl)

tensor([[ 75.,  63.,  48.],
        [ 91.,  88.,  66.],
        [ 84., 137.,  57.],
        [108.,  41.,  36.],
        [ 68.,  98.,  72.]])
tensor([[ 54.,  71.],
        [ 84., 111.],
        [122., 143.],
        [ 20.,  40.],
        [101., 117.]])
tensor([[68., 98., 72.],
        [75., 63., 48.]])
tensor([[101., 117.],
        [ 54.,  71.]])
Parameter containing:
tensor([[ 0.3741,  0.1702, -0.1889],
        [-0.1988,  0.5024, -0.3746]], requires_grad=True)
Parameter containing:
tensor([ 0.0806, -0.5676], requires_grad=True)
Epoch [10/1000], Loss: 68.5174
Epoch [20/1000], Loss: 85.3458
Epoch [30/1000], Loss: 95.6487
Epoch [40/1000], Loss: 124.4186
Epoch [50/1000], Loss: 67.7092
Epoch [60/1000], Loss: 53.6633
Epoch [70/1000], Loss: 73.4481
Epoch [80/1000], Loss: 33.6344
Epoch [90/1000], Loss: 63.5969
Epoch [100/1000], Loss: 38.8214
Epoch [110/1000], Loss: 32.3306
Epoch [120/1000], Loss: 23.1528
Epoch [130/1000], Loss: 0.7507
Epoch [140/1000], Loss: 14.0357
Epoch [150/1000], Loss: 0.9

In [8]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 55.9152,  73.4186],
        [ 81.9363, 104.2038],
        [122.1121, 143.3028],
        [ 19.9337,  41.6064],
        [101.1401, 120.1965]], grad_fn=<AddmmBackward>)

In [9]:
model(torch.tensor([[72, 65., 42.]]))  #testing

tensor([[55.4840, 71.9879]], grad_fn=<AddmmBackward>)

In [10]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch_optimizer as optim
from adabelief_pytorch import AdaBelief
import numpy as np


# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            

# Input (x, y, z)
inputs = np.array([[75, 63, 48], 
                   [91, 88, 66], 
                   [84, 137, 57], 
                   [108, 41, 36], 
                   [68, 98, 72]], dtype='float32')

# Targets (a, b)
targets = np.array([[54, 71], 
                    [84, 111], 
                    [122, 143], 
                    [20, 40], 
                    [101, 117]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

# Define data loader
batch_size = 2  # should be << number of observations
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break
    
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

# Define loss function
loss_fn = F.mse_loss

#Adabelief Optimizer
#opt = optim.AdaBelief(model.parameters(), lr=1e-3, betas=(0.9, 0.999), eps=1e-8)
opt = AdaBelief(model.parameters(), lr=1e-5, eps=1e-16, betas=(0.9, 0.999), print_change_log = False)

fit(1000, model, loss_fn, opt, train_dl)

tensor([[ 75.,  63.,  48.],
        [ 91.,  88.,  66.],
        [ 84., 137.,  57.],
        [108.,  41.,  36.],
        [ 68.,  98.,  72.]])
tensor([[ 54.,  71.],
        [ 84., 111.],
        [122., 143.],
        [ 20.,  40.],
        [101., 117.]])
tensor([[108.,  41.,  36.],
        [ 91.,  88.,  66.]])
tensor([[ 20.,  40.],
        [ 84., 111.]])
Parameter containing:
tensor([[-0.0642,  0.2038,  0.3296],
        [ 0.3397, -0.4588,  0.1628]], requires_grad=True)
Parameter containing:
tensor([ 0.2240, -0.0778], requires_grad=True)
Weight decoupling enabled in AdaBelief
Rectification enabled in AdaBelief
Epoch [10/1000], Loss: 1599.5325
Epoch [20/1000], Loss: 1026.4380
Epoch [30/1000], Loss: 1597.9998
Epoch [40/1000], Loss: 3481.8701
Epoch [50/1000], Loss: 1028.2096
Epoch [60/1000], Loss: 591.2183
Epoch [70/1000], Loss: 590.3581
Epoch [80/1000], Loss: 589.4880
Epoch [90/1000], Loss: 1589.3118
Epoch [100/1000], Loss: 31.5823
Epoch [110/1000], Loss: 1033.9594
Epoch [120/1000], Loss: 58

In [11]:
# Generate predictions
preds = model(inputs)
preds

tensor([[54.7667, 66.7601],
        [74.7739, 83.9230],
        [90.1538, 73.5396],
        [42.8573, 83.7607],
        [79.7780, 71.2603]], grad_fn=<AddmmBackward>)

In [12]:
model(torch.tensor([[72, 65., 42.]]))  #testing

tensor([[52.5423, 62.1362]], grad_fn=<AddmmBackward>)